# Buenos Aires Cultural Events Dataset

### BUSINESS CHALLENGE:

Create a product that allows us to see a quick view of current cultural events in Buenos Aires classified by type of event and venue. It should provide information about all events and related links from different venues in Buenos Aires, so we can easily pick what we want to do this week.

In [1]:
import os
import pandas as pd
print("cwd:", os.getcwd())
print("src exists:", os.path.exists(os.path.abspath("../src")))
print("scraper exists:", os.path.exists(os.path.abspath("../src/scraper.py")))

cwd: /Users/victoriayuzova/Data-Science-Projects/ba-events-recommender/notebooks
src exists: True
scraper exists: True

In [2]:
# imports
# If these fail, please check you're running from an 'activated' environment with (llms) in the command prompt
import os
import sys
import json
import importlib

from dotenv import load_dotenv
from IPython.display import Markdown, display, update_display
from openai import OpenAI

# Force the notebook to import the *local* ../src/scraper.py (not the pip package named `scraper`)
src_path = os.path.abspath("../src")
if src_path not in sys.path:
    sys.path.insert(0, src_path)
if "scraper" in sys.modules:
    del sys.modules["scraper"]

scraper = importlib.import_module("scraper")
fetch_website_links = scraper.fetch_website_links
fetch_website_contents = scraper.fetch_website_contents
extract_links_from_homepages = scraper.extract_links_from_homepages
build_classified_events_dataset = scraper.build_classified_events_dataset

/Users/victoriayuzova/Data-Science-Projects/ba-events-recommender/.venv/lib/python3.9/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(

In [3]:
import json
from pathlib import Path

p = Path.cwd().parent / "src" / "homepage_urls.json"  # because cwd is notebooks/
with p.open("r", encoding="utf-8") as f:
    homepage_urls = json.load(f)["homepage_urls"]

homepage_urls

['https://complejoteatral.gob.ar/',
 'https://malba.org.ar/',
 'https://turismo.buenosaires.gob.ar/es/eventos',
 'https://www.bellasartes.gob.ar/agenda/']

In [4]:
df_links = extract_links_from_homepages(
    homepage_urls=homepage_urls,
    fetch_website_links_fn=fetch_website_links,
    keep_same_domain=False,  # important for ticket domains
    out_dir="../data/raw",   # relative path is cleaner
    filename="01_all_links.csv"
)

df_links.head()

Saved 399 rows to: ../data/raw/2026-03-16/01_all_links.csv

,run_date,scraped_at,page_url,event_url_raw,event_url_abs,link_id
0,2026-03-16,2026-03-16T11:37:21,https://complejoteatral.gob.ar/,http://buenosaires.gob.ar/,http://buenosaires.gob.ar/,3cd0a6fbe45556781bd85be6f1ab1d74
1,2026-03-16,2026-03-16T11:37:21,https://complejoteatral.gob.ar/,https://complejoteatral.gob.ar/agenda?fecha=16...,https://complejoteatral.gob.ar/agenda?fecha=16...,e8293ea7a4942581ca1d7be79c4f5e9c
2,2026-03-16,2026-03-16T11:37:21,https://complejoteatral.gob.ar/,https://complejoteatral.gob.ar/pdf/temporada20...,https://complejoteatral.gob.ar/pdf/temporada20...,bb6f5d43ebd6fb57389f315068d57fee
3,2026-03-16,2026-03-16T11:37:21,https://complejoteatral.gob.ar/,https://complejoteatral.gob.ar/ver/visitas_gui...,https://complejoteatral.gob.ar/ver/visitas_gui...,490e1ba143103982811544dfc0542a9b
4,2026-03-16,2026-03-16T11:37:21,https://complejoteatral.gob.ar/,https://complejoteatral.gob.ar/paginas/teatros...,https://complejoteatral.gob.ar/paginas/teatros...,8393f13dbdf20717b5095e801cf12ac3

## Step 1. Use LLM to pick relevant links

### We will call an LLM so it picks only relevant links with events

We will use "one shot prompting" in which we provide an example of how it should respond in the prompt.

This is an excellent use case for an LLM, because it requires nuanced understanding - hard coding each scenario would take us quite some time.

In [5]:
# Initialize and constants

load_dotenv(override=True)
api_key = os.getenv('OPENAI_API_KEY')

# Default model you can use elsewhere
MODEL = 'gpt-5-nano'

# Use a steadier model for link selection (avoid long hangs/timeouts)
LINK_MODEL = 'gpt-4.1-mini'

# Add a client-side timeout so a single slow request doesn't hang the notebook
openai = OpenAI(timeout=180)

In [6]:
# 1) Group candidates per homepage (IMPORTANT: use the filtered df2)
grouped = df_links.groupby("page_url")["event_url_raw"].apply(list).to_dict()

payloads = [
    {"homepage_url": page_url, "institution": None, "links": links}
    for page_url, links in grouped.items()
]

link_system_prompt = """
You are selecting event-related links for a Buenos Aires cultural events scraper.

Input JSON keys:
- homepage_url: string
- institution: string or null
- links: array of absolute URLs (strings)

Pick ONLY links useful to find current/upcoming cultural events:
- event listing pages (agenda / programacion / calendario)
- event detail pages
- ticket purchase pages
- (optional) program PDFs (ONLY if they are clearly about programming/season/events)

Exclude:
- terms/privacy, about, contact, donations, newsletters, login, accessibility pages, generic navigation
- social media

Rules:
- Do NOT invent URLs. Every URL must be exactly one of input.links
- Return at most 30 links
- Return ONLY valid JSON (no markdown/no prose) with schema:

{
  "homepage_url": "<string>",
  "institution": null,
  "links": [{"url": "<string>"}]
}
""".strip()

def select_relevant_links(payload: dict) -> dict:
    # Make sure content is string (fixes your earlier BadRequestError)
    payload_text = json.dumps(payload, ensure_ascii=False)

    print(f"Selecting relevant links for {payload['homepage_url']} by calling {LINK_MODEL}")

    response = openai.chat.completions.create(
        model=LINK_MODEL,  # use your steadier model here
        messages=[
            {"role": "system", "content": link_system_prompt},
            {"role": "user", "content": payload_text},
        ],
        response_format={"type": "json_object"},
        temperature=0,
    )

    result = json.loads(response.choices[0].message.content)

    # Safety: keep only URLs that were in the input (no hallucinations)
    input_set = set(payload["links"])
    cleaned = [x for x in result.get("links", []) if x.get("url") in input_set]

    result["homepage_url"] = payload["homepage_url"]
    result["institution"] = payload.get("institution")
    result["links"] = cleaned[:30]

    print(f"Found {len(result['links'])} relevant links")
    return result

outs = [select_relevant_links(p) for p in payloads]

df_selected = pd.concat(
    [
        pd.DataFrame(o["links"]).assign(
            homepage_url=o.get("homepage_url"),
            institution=o.get("institution")
        )
        for o in outs
    ],
    ignore_index=True
)

df_selected.head()

Selecting relevant links for https://complejoteatral.gob.ar/ by calling gpt-4.1-mini
Found 30 relevant links
Selecting relevant links for https://malba.org.ar/ by calling gpt-4.1-mini
Found 22 relevant links
Selecting relevant links for https://turismo.buenosaires.gob.ar/es/eventos by calling gpt-4.1-mini
Found 30 relevant links
Selecting relevant links for https://www.bellasartes.gob.ar/agenda/ by calling gpt-4.1-mini
Found 14 relevant links

,url,homepage_url,institution
0,https://complejoteatral.gob.ar/agenda?fecha=16...,https://complejoteatral.gob.ar/,None
1,https://complejoteatral.gob.ar/pdf/temporada20...,https://complejoteatral.gob.ar/,None
2,https://complejoteatral.gob.ar/ver/visitas_gui...,https://complejoteatral.gob.ar/,None
3,https://complejoteatral.gob.ar/ver/GERALD-CLAY...,https://complejoteatral.gob.ar/,None
4,https://www.tuentrada.com/jazz-bsas-ctba,https://complejoteatral.gob.ar/,None

In [7]:
df_selected.groupby("homepage_url")["url"].count().sort_values(ascending=False)

homepage_url
https://complejoteatral.gob.ar/                  30
https://turismo.buenosaires.gob.ar/es/eventos    30
https://malba.org.ar/                            22
https://www.bellasartes.gob.ar/agenda/           14
Name: url, dtype: int64

In [8]:
from datetime import datetime
import os

run_date = datetime.utcnow().strftime("%Y-%m-%d")

save_folder = f"../data/raw/{run_date}"
os.makedirs(save_folder, exist_ok=True)

df_selected.to_csv(f"{save_folder}/02_relevant_links.csv", index=False)

In [9]:
link_system_prompt = """
You are selecting event-related links for a Buenos Aires cultural events scraper.

You will receive a JSON object as input with keys:
- homepage_url: string
- institution: string or null
- links: array of absolute URLs (strings)

Your job:
- Pick ONLY links that are relevant for finding current/upcoming cultural events (agenda/listings, event detail pages, ticket purchase pages, program PDFs, calendars).
- Exclude terms/privacy, contact/about, donations/sponsors, newsletters, login, generic navigation, accessibility pages, and any social media.
- Do NOT invent new URLs. Every returned URL must come from input.links.
- Return at most 30 links.

Return ONLY valid JSON (no markdown, no prose) with this schema:

{
  "homepage_url": "<string>",
  "institution": "<string or null>",
  "links": [
    {
      "url": "<string>"
    }
  ]
}
"""

In [10]:
def get_links_user_prompt(payload_json_links):
    user_prompt = f"""
Here is the list of links on the website in json format: {payload_json_links} -
Please decide which of these are relevant web links for a brochure listing current cultural
evens in Buenos Aires.
Do not include Terms of Service, Privacy, email, social media links, or general descriptions of the theater that´s not related to any event.

Links (some might be relative links):

"""
    links = fetch_website_links(payload_json_links)
    user_prompt += "\n".join(links)
    return user_prompt

In [11]:
def select_relevant_links(payload_json_links):
    print(f"Selecting relevant links for {payload_json_links} by calling {MODEL}")
    response = openai.chat.completions.create(
        model=MODEL,
        messages=[
            {"role": "system", "content": link_system_prompt},
            {"role": "user", "content": payload_json_links}
        ],
        response_format={"type": "json_object"}
    )
    result = response.choices[0].message.content
    links = json.loads(result)
    print(f"Found {len(links['links'])} relevant links")
    return links

In [12]:
for i, p in enumerate(payloads):
    if not isinstance(p, str):
        print(i, type(p))
        break

0 <class 'dict'>

In [13]:
outs = [select_relevant_links(json.dumps(p, ensure_ascii=False)) for p in payloads]

df_selected = pd.concat(
    [pd.DataFrame(o["links"]).assign(homepage_url=o.get("homepage_url"), institution=o.get("institution"))
     for o in outs],
    ignore_index=True
)

df_selected

Selecting relevant links for {"homepage_url": "https://complejoteatral.gob.ar/", "institution": null, "links": ["http://buenosaires.gob.ar/", "https://complejoteatral.gob.ar/agenda?fecha=16-03-2026", "https://complejoteatral.gob.ar/pdf/temporada2026.pdf", "https://complejoteatral.gob.ar/ver/visitas_guiadas_al_teatro_san_martín", "https://complejoteatral.gob.ar/paginas/teatros-accesibles", "https://complejoteatral.gob.ar/paginas/info-contacto", "https://www.instagram.com/elSanMartinCTBA", "https://www.twitter.com/elSanMartinCTBA", "https://www.facebook.com/TeatroSanMartinCTBA", "https://complejoteatral.gob.ar/#programacion", "/noticias/", "https://complejoteatral.gob.ar/companias-estables/ballet-contemporaneo", "https://complejoteatral.gob.ar/companias-estables/grupo-de-titiriteros", "https://complejoteatral.gob.ar/paginas/teatros", "https://complejoteatral.gob.ar/paginas/legado-y-mision", "https://complejoteatral.gob.ar/paginas/autoridades", "https://complejoteatral.gob.ar/paginas/espacios-en-alquiler", "https://complejoteatral.gob.ar/paginas/sponsoreo-y-donaciones", "http://www.fundacionamigostsm.org.ar/", "https://complejoteatral.gob.ar/paginas/visitas-guiadas", "https://complejoteatral.gob.ar/paginas/visita-360", "https://www.youtube.com/@TeatroSanMartinCTBA", "https://complejoteatral.gob.ar/notas/en-off", "https://complejoteatral.gob.ar/paginas/recursos-para-espectadores", "https://complejoteatral.gob.ar/paginas/centro-de-documentacion-centro-de-vestuario", "https://centrodevestuario.complejoteatral.gob.ar", "https://complejoteatral.gob.ar/paginas/newsletter", "https://complejoteatral.gob.ar/paginas/formacion-2021#taller-de-danza", "https://complejoteatral.gob.ar/paginas/formacion-2021#taller-de-titeres", "https://complejoteatral.gob.ar/paginas/formacion-2021#escuela-de-oficios", "https://complejoteatral.gob.ar/paginas/formacion-2021#la-escuela-al-teatro", "https://complejoteatral.gob.ar/ver/GERALD-CLAYTON-TRIO", "https://www.tuentrada.com/jazz-bsas-ctba", "https://complejoteatral.gob.ar/ver/la_gaviota", "https://entradasba.buenosaires.gob.ar/evento/d90f82ed-ec8f-46cf-b8b2-48e665a36fc3", "https://complejoteatral.gob.ar/ver/los-pilares-de-la-sociedad", "https://entradasba.buenosaires.gob.ar/evento/42523311-973e-4a52-b2ee-63a59c48a2b7", "https://complejoteatral.gob.ar/ver/baco-polaco", "https://entradasba.buenosaires.gob.ar/evento/f94c1c9a-151e-49a8-8ed8-c9aa9d0464c3", "https://complejoteatral.gob.ar/ver/festival_el_tornillo", "https://complejoteatral.gob.ar/noticia/136", "https://complejoteatral.gob.ar/noticia/131", "https://complejoteatral.gob.ar/noticia/134", "https://complejoteatral.gob.ar/noticia/135", "https://www.bancociudad.com.ar/", "https://entradasba.buenosaires.gob.ar/evento/f163b37c-bb5f-48b0-a250-5d4293030f3f", "https://complejoteatral.gob.ar/ver/paraiso", "https://www.ticketek.com.ar/invasiones-i/teatro-san-martin", "https://complejoteatral.gob.ar/ver/invasiones-1", "https://entradasba.buenosaires.gob.ar/evento/67826298-9dd3-4680-bf3f-d3d652a513c0", "https://complejoteatral.gob.ar/ver/chau-macoco", "https://tuentrada.com/jazz-bsas-ctba", "https://complejoteatral.gob.ar/ver/jazz_buenos_aires", "https://www.tuentrada.com/eventos/detalle/jazz-buenos-aires-26-tsm/916415957944", "https://paraisoclub.squarespace.com/entradascentroamerica", "https://complejoteatral.gob.ar/ver/centroamerica", "https://entradasba.buenosaires.gob.ar/evento/99a82897-d153-42c7-9a67-4fc2401ee7ee", "https://complejoteatral.gob.ar/ver/viaje-al-amor-brujo", "https://entradasba.buenosaires.gob.ar/evento/462df27d-6ff4-4444-a48b-c5e0a6c37d6e", "https://complejoteatral.gob.ar/ver/numancia", "https://entradasba.buenosaires.gob.ar/evento/2884a22e-3b78-4d6d-a264-691889991cae", "https://complejoteatral.gob.ar/ver/boys -in-the-sand", "https://entradasba.buenosaires.gob.ar/evento/473c4e09-58b1-4d58-a912-c0074a420787", "https://complejoteatral.gob.ar/ver/alejandra-y-los-mundos", "https://complejoteatral.gob.ar/storage/programacion/March2026/r3vR23nTOfMcAfBuuKCn.pdf", "https://complejoteatral.gob.ar/ver/narrar-en-presente", "https://complejoteatral.gob.ar/ver/territorio-efimero", "https://complejoteatral.gob.ar/ver/milonga_en_el_plata", "https://entradasba.buenosaires.gob.ar/evento/d878379c-68ea-48ad-809f-139873fc7acc", "https://complejoteatral.gob.ar/ver/Las-furias-y-Las-modelos", "https://complejoteatral.gob.ar/pdf/programa-las-furias-y-las-modelos.pdf", "https://entradasba.buenosaires.gob.ar/evento/cd117e97-ba41-4e74-b654-9b05c1cd9f31", "https://complejoteatral.gob.ar/ver/Boris-Karloff:-el hombre-y-la- bestia - Parte 1", "https://complejoteatral.gob.ar/pdf/programa-boris-karloff.pdf", "https://entradasba.buenosaires.gob.ar/evento/1ba245d3-8c08-409f-9807-f191a92f19cf", "https://complejoteatral.gob.ar/ver/Garage-Olimpo", "https://complejoteatral.gob.ar/pdf/programa-garage-olimpo.pdf", "https://www.timbre4.com/teatro/1241-pasion-una-tragedia-argentina.html"]} by calling gpt-5-nano
Found 28 relevant links
Selecting relevant links for {"homepage_url": "https://malba.org.ar/", "institution": null, "links": ["https://malba.liit.com.ar/decidir/", "https://malba.liit.com.ar/amigos/malba_amigo.php", "https://malba.org.ar/en/", "https://www.instagram.com/museomalba", "https://www.facebook.com/museomalba/", "https://x.com/MuseoMalba", "https://www.youtube.com/museomalba", "https://www.tiktok.com/@museomalba", "https://malba.org.ar/visitar/", "https://malba.org.ar/visitar/#dias", "https://malba.org.ar/visitar/#llegar", "https://malba.org.ar/visitar/#visitas", "https://malba.org.ar/coronado/", "https://malba.org.ar/visitar/#accesibilidad", "https://malba.org.ar/museo/", "https://www.malbapuertos.org.ar/", "https://malba.org.ar/agenda-hoy/", "https://malba.org.ar/eventos/sobre/virtual/", "https://malba.org.ar/exposiciones-actuales/", "https://malba.org.ar/evento/tercer-ojo__coleccion-costantini_en-malba/", "https://malba.org.ar/evento/olga-de-amaral-cuerpo-textil/", "https://malba.org.ar/evento/fernanda-laguna-mi-corazon-es-un-iman/", "https://malba.org.ar/coleccion/", "https://malba.org.ar/coleccion/#historia", "https://malba.org.ar/coleccion/#imperdibles", "https://coleccion.malba.org.ar/", "https://malba.org.ar/cine/", "https://malba.org.ar/literatura/", "https://malba.org.ar/educacion/", "https://malba.org.ar/programas-publicos/", "https://malba.org.ar/amigos/", "https://malba.org.ar/peliculas/", "https://malba.org.ar/cursos/", "https://malba.org.ar/conferencias/", "https://malba.org.ar/recorridos/", "https://malba.org.ar/talleres/", "https://tienda.malba.org.ar/", "https://tienda.malba.org.ar/collections/publicaciones-malba", "https://tienda.malba.org.ar/collections/merchandising", "https://tienda.malba.org.ar/collections/objetos", "https://tienda.malba.org.ar/collections/libros", "https://malba.org.ar/category/noticias/", "https://malba.org.ar/category/publicaciones/", "https://www.malbaplus.org.ar/", "https://malba.org.ar/textuales/", "https://malba.org.ar/colabora/", "https://malba.org.ar/colabora/#haceteamigo", "https://malba.org.ar/colabora/#benefactores", "https://malba.org.ar/colabora/#sponsors", "https://malba.org.ar/colabora/#eventos", "https://www.youtube.com/watch?v=BGbhV90qeRo", "https://malba.org.ar/evento/telares-como-textos-piel-social-de-la-cultura-andina/", "https://malba.org.ar/evento/recorridos-abiertos-en-portugues__tupi-or-not-tupi-trayectos-brasilenos-en-el-arte-latinoamericano/", "https://malba.org.ar/evento/micro-mediaciones-por-mi-corazon-es-un-iman/", "https://malba.liit.com.ar/decidir/?cine=si", "https://malba.org.ar/evento/fernanda-laguna-mi-corazon-es-un-iman-1992-2025/", "https://malba.org.ar/evento/anima-y-animus-en-carl-g-jung-el-desarrollo-psiquico-y-los-opuestos-arquetipicos/", "https://malba.org.ar/evento/modos-de-hacer-paisajes-tejidos/", "https://malba.org.ar/evento/hacer-familia/", "https://malba.org.ar/evento/el-cuerpo-del-color-el-ikat-tridimensional-de-olga-de-amaral/", "https://malba.org.ar/evento/hitchcock-x-4/", "https://malba.org.ar/evento/recorridos-abiertos-por-cuerpo-textil/", "https://malba.org.ar/evento/los-dias-chinos/", "https://malba.org.ar/evento/belleza-y-felicidad-autobiografia-de-una-amistad/", "https://malba.org.ar/evento/cien-anos-mas-tarde-libros-argentinos-de-1926-arlt-guiraldes-quiroga-y-borges/", "https://malba.org.ar/evento/cuerpo-textil/", "https://malba.org.ar/evento/el-arte-de-escribir-una-vida-loca-introduccion-a-la-obra-literaria-de-fernanda-laguna/", "https://malba.org.ar/evento/pin-de-fartie/", "https://malba.org.ar/evento/tardes-de-soledad/", "https://malba.org.ar/inauguro-mi-corazon-es-un-iman/", "https://malba.org.ar/inauguracion-olga-de-amaral/", "https://malba.org.ar/rem-2026__los-autores-seleccionados-para-participar-de-la-residencia-de-escritores-en-2026/", "https://malba.org.ar/rodrigo-moura-concluye-su-ciclo-como-director-artistico-de-malba/", "https://coleccion.malba.org.ar/abaporu/", "https://coleccion.malba.org.ar/manifestacion/", "https://coleccion.malba.org.ar/autorretrato-con-chango-y-loro/", "https://coleccion.malba.org.ar/retrato-de-ramon-gomez-de-la-serna/", "https://coleccion.malba.org.ar/the-disasters-of-mysticism/", "https://coleccion.malba.org.ar/la-manana-verde/", "https://coleccion.malba.org.ar/la-cancion-del-pueblo/", "https://coleccion.malba.org.ar/festa-de-sao-joao/", "https://coleccion.malba.org.ar/baile-en-tehuantepec/", "https://coleccion.malba.org.ar/paisaje-exuberante/", "https://coleccion.malba.org.ar/composition-symetrique-universelle-en-blanc-et-noir/", "https://tienda.malba.org.ar/collections/pop-brasil-vanguardia-y-nueva-figuracion-1960s-70s", "https://tienda.malba.org.ar/collections/tercer-ojo", "https://tienda.malba.org.ar/products/malba-cuerpo-textil", "https://malba.org.ar/newsletter/", "https://www.halaxia.com/empresa/malba", "https://malba.org.ar/contacto/", "https://malba.org.ar/politicas-de-privacidad/", "https://malba.org.ar/aviso-legal/"]} by calling gpt-5-nano
Found 30 relevant links
Selecting relevant links for {"homepage_url": "https://turismo.buenosaires.gob.ar/es/eventos", "institution": null, "links": ["/es", "/es/node/72732", "/es/node/73022", "/es/node/71844", "/es/node/68132", "/es/node/71271", "/es/node/49330", "/es/node/67084", "/es/node/49510", "/es/node/72956", "/es/node/48862", "/es/node/48937", "/es/node/47504", "/es/node/71260", "/es/node/69277", "/es/node/68444", "/es/node/68638", "/es/node/48089", "/es/node/48335", "/es/node/72264", "/es/node/72766", "/es/node/70664", "/es/node/49646", "/es/article/corrientes-24-h", "/es/article/fuerza-bruta", "/es/propuestaslolla", "/es/article/carne-festival-de-parrillas", "/es/article/expo-cupcakes", "/es/article/tc-2000", "/es/article/new-balance-10k-buenos-aires", "/es/article/fito-p%C3%A1ez", "/es/article/mandinga-tattoo-expo-buenos-aires", "/es/article/acdc", "/es/article/nuestros-caballos", "/es/article/tan-bi%C3%B3nica", "/es/article/ba-flota", "/es/article/parador-konex", "/es/article/el-horizonte-de-keops", "/es/article/candlelight", "/es/article/sushi-world-cup", "/es/article/bioferia", "/es/article/bafici", "/es/article/feria-internacional-del-libro", "/es/article/maratana", "/es/article/25k-new-balance", "/es/article/mapa-feria-de-arte", "/es/article/caminos-y-sabores", "/es/article/exposici%C3%B3n-rural", "/es/article/fit-feria-internacional-del-turismo", "/es/article/arteba", "/es/article/cumbia-konex-10-a%C3%B1os", "/es/article/festival-nuevo-d%C3%ADa", "/es/article/billboard-summer-festival", "/es/article/filbita", "/es/article/sting-30", "/es/article/concierto-de-la-orquesta-filarm%C3%B3nica-de-buenos-aires", "/es/article/feria-picnic-gourmet", "/es/article/fiesta-la-m%C3%A1gica", "/es/article/pizzaman%C3%ADa", "/es/article/expohobby-0", "/es/article/pascuas-en-la-ciudad", "/es/article/fauna-festival-universitario", "/es/article/mercado-fusi%C3%B3n", "/es/article/river-plate-vs-boca-juniors", "/es/article/sunsetstrip-buenos-aires", "/es/article/neo-pistea", "/es/article/nodo-circuito-de-galer%C3%ADas-0", "/es/article/lit-killah", "/es/article/premier-p%C3%A1del", "/es/article/fiesta-junina", "/es/article/15k-adizero", "/es/article/la-dorada", "/es/article/diego-torres", "/es/article/la-chocolaterie", "/es/article/la-renga", "/es/article/carrera-de-la-independencia", "/es/article/sabores-de-la-patria", "/es/article/eruca-sativa", "/es/article/nb-30k-buenos-aires", "/es/article/turismo-pista-y-turismo-carretera-2000", "/es/article/chorifest", "/es/article/wtt-contender-buenos-aires-2025", "/es/vacacionesdeinvierno", "/es/article/feria-del-libro-infantil-y-juvenil", "/es/article/disney-ice-0", "/es/article/expocel%C3%ADaca", "/es/article/campeonato-mundial-del-alfajor", "/es/article/d%C3%ADa-del-ni%C3%B1o-en-la-ciudad", "/es/article/viv%C3%AD-lo-mejor-del-tc-en-buenos-aires", "/es/article/21k-de-buenos-aires", "/es/article/hotelga", "/es/article/bada", "/es/article/tango-ba-festival-y-mundial", "/es/article/pint%C3%B3-bodeg%C3%B3n", "/es/article/las-pastillas-del-abuelo", "/es/article/ani-con-argentina", "/es/article/ba-est%C3%A1-de-moda", "/es/article/exig%C3%AD-buen-caf%C3%A9", "/es/article/la-noche-de-la-pizza-y-la-empanada", "/es/article/fiba-festival-internacional-de-buenos-aires", "/es/article/marat%C3%B3n-internacional-de-buenos-aires-42k", "/es/article/filba", "/es/article/semana-negra-ba", "/es/article/buenos-aires-cumbia-0", "/es/article/sabor-buenos-aires", "/es/article/leer-y-comer", "/es/article/festival-de-la-milanesa", "/es/article/yami-safdie", "/es/article/creamfields", "/es/article/open-house-buenos-aires", "/es/article/cafecito-ba", "/es/article/feria-sin-tacc", "/es/article/festival-del-asado-y-la-empanada", "/es/article/la-feria-francesa", "/es/article/gran-fondo-argentina", "/es/article/carlos-vives", "/es/article/la-noche-de-los-bares-notables", "/es/article/pinta-baphoto", "/es/article/linkin-park-zero-world-tour", "/es/article/m%C3%A9xico-celebra-el-d%C3%ADa-de-muertos", "/es/article/tiago-pzk", "/es/article/semana-del-orgullo", "/es/article/la-noche-de-los-museos", "/es/article/dua-lipa", "/es/article/tecweek-0", "/es/article/noche-de-las-heladerias", "/es/article/la-noche-de-los-alfajores", "/es/article/oasis", "/es/article/devconnect-arg", "/es/article/la-noche-de-las-librer%C3%ADas", "/es/article/luciano-pereyra", "/es/article/futcon-2025", "/es/article/retiro-abierto", "/es/article/buenos-aires-rojo-sangre", "/es/article/la-noche-de-los-templos", "/es/article/campeonato-argentino-abierto-de-polo", "/es/article/festival-ciudad-joven-ba", "/es/article/comic-con-argentina", "/es/article/bizarren-miusik-parti", "/es/article/abel-pintos", "/es/article/shakira-las-mujeres-ya-no-lloran-world-tour", "/es/article/abierto-argentino-de-pato-la-gran-final", "/es/article/lali", "/es/article/road-australia", "/es/article/airbag", "/es/article/duki-world-tour", "/es/article/navidad-en-la-ciudad-0", "/es/article/bresh", "/es/article/pm-open-air", "/es/article/my-chemical-romance", "/es/article/nonpalidece", "/es/article/killer-queen", "/es/article/food-fest", "/es/article/la-vela-puerca", "/es/article/atp-de-buenos-aires", "/es/article/sin-bandera", "/es/article/bad-bunny", "/es/article/ultra-buenos-aires", "/es/article/ano-nuevo-chino", "/es/article/buenos-aires-extremo-edici%C3%B3n-verano", "/es/article/afters-ba", "/es/article/col%C3%B3n-inmersivo-monet", "/es/article/nicki-nicole-sinf%C3%B3nico", "/es/article/burger-fest", "/es/article/festival-buena-vibra", "/es/article/ciudad-joven-ba", "/es/article/%C3%A1stor-piazzolla-eterno", "/es/article/la-banda-de-carlitos-y-euge-quevedo", "/es/article/festival-planetario", "/es/article/carnaval-porteno", "/es/article/viven-dinosaurios", "/es/article/super-jump", "/es/article/art-masters", "/es/article/cultura-de-verano", "/es/article/cazzu", "/es/article/big-time-rush", "/es/article/pablo-albor%C3%A1n", "/es/article/la-noche-de-las-hamburgueser%C3%ADas", "/es/article/q%E2%80%99lokura", "/es/article/chayanne", "/es/article/alejandro-sanz", "/es/article/mayuman%C3%A1", "/es/node/55855", "/es/node/70582", "/es/node/66236", "/es/node/49588", "/es/node/67111", "/es/city-news", "/es/node/49886", "/es/node/72565", "https://ba.tours/", "https://play.google.com/store/apps/details?id=ar.gob.buenosaires.baturismo", "https://apps.apple.com/us/app/ba-turismo/id984827193", "/es/node/70621"]} by calling gpt-5-nano
Found 29 relevant links
Selecting relevant links for {"homepage_url": "https://www.bellasartes.gob.ar/agenda/", "institution": null, "links": ["/", "/paginas/planea-tu-visita/", "/coleccion/", "/exhibiciones/", "/paginas/museo/", "/lang/pt/?path=/agenda/", "/lang/en/?path=/agenda/", "https://www.facebook.com/MNBAArgentina", "https://twitter.com/BellasArtesAR", "https://www.flickr.com/photos/186501806@N04/albums", "https://www.instagram.com/bellasartesargentina/", "https://www.youtube.com/user/MNBAdigital", "/coleccion/buscar", "/agenda/2026/3/1/", "/agenda/2026/3/31/", "/agenda/circulacion-en-planta-baja-con-sentido-unico/", "/agenda/imperdibles_2/", "/agenda/visitas-egipt/", "/agenda/lsa-egipt/", "/agenda/rodin_4/", "/agenda/paseo-escultur/", "/agenda/boceto-egipto/", "/agenda/desafioss/", "/agenda/recorrido-por-la-planta-baja-y-primer-piso/", "/agenda/entre-tela/", "/agenda/catalogo-dibujos-antiguos/", "/agenda/visita-acc_1/", "/coleccion/buscar/#resultados", "/coleccion/arte-argentino/", "/coleccion/obras-maestras/", "/noticias", "/publicaciones", "https://museoartedecorativo.cultura.gob.ar/", "https://museohistoriconacional.cultura.gob.ar/", "http://museodeltraje.cultura.gob.ar"]} by calling gpt-5-nano
Found 16 relevant links

,url,homepage_url,institution
0,https://complejoteatral.gob.ar/agenda?fecha=16...,https://complejoteatral.gob.ar/,None
1,https://complejoteatral.gob.ar/pdf/temporada20...,https://complejoteatral.gob.ar/,None
2,https://complejoteatral.gob.ar/ver/GERALD-CLAY...,https://complejoteatral.gob.ar/,None
3,https://complejoteatral.gob.ar/ver/la_gaviota,https://complejoteatral.gob.ar/,None
4,https://complejoteatral.gob.ar/ver/jazz_buenos...,https://complejoteatral.gob.ar/,None
...,...,...,...
98,/agenda/entre-tela/,https://www.bellasartes.gob.ar/agenda/,None
99,/agenda/catalogo-dibujos-antiguos/,https://www.bellasartes.gob.ar/agenda/,None
100,/agenda/visita-acc_1/,https://www.bellasartes.gob.ar/agenda/,None
101,/lang/pt/?path=/agenda/,https://www.bellasartes.gob.ar/agenda/,None
102,/lang/en/?path=/agenda/,https://www.bellasartes.gob.ar/agenda/,None

In [14]:
df_selected.to_csv("relevant_links.csv", index=False)

## Second step: lets classify those links

Assemble all the details into another prompt to GPT-5-nano

In [15]:

df_events = build_classified_events_dataset(
    df_relevant = pd.read_csv("relevant_links.csv"),  # df_selected already has url + homepage_url
    fetch_website_contents_fn=fetch_website_contents,
    openai_client=openai,
    model="gpt-4.1-mini",
    out_dir="../data/raw",
    filename="03_events.csv",
    #limit=30,
)
df_events.head()

Saved 103 rows to: ../data/raw/2026-03-16/03_events.csv

,url,homepage_url,page_type,title,summary,category,start_date,start_time,venue,price,is_free,tags,confidence,run_date,extracted_at
0,https://complejoteatral.gob.ar/agenda?fecha=16...,https://complejoteatral.gob.ar/,listing,Agenda | Complejo Teatral de Buenos Aires,Listing of theatrical events around 16 March 2...,theatre,None,None,None,None,None,"[teatro, agenda, temporada internacional, comp...",0.80,2026-03-16,2026-03-16T11:43:12+00:00
1,https://complejoteatral.gob.ar/pdf/temporada20...,https://complejoteatral.gob.ar/,pdf,None,None,other,None,None,None,None,None,[],0.30,2026-03-16,2026-03-16T11:43:12+00:00
2,https://complejoteatral.gob.ar/ver/GERALD-CLAY...,https://complejoteatral.gob.ar/,event_detail,GERALD CLAYTON TRIO,Comienza el ciclo de jazz en el Teatro San Mar...,music,2026-03-17,20:00,"Teatro San Martín, Sala Martín Coronado","Platea Filas 2 a 5 $85.000, Platea Filas 6 a 2...",False,"[jazz, Gerald Clayton, Trio, Teatro San Martín...",0.95,2026-03-16,2026-03-16T11:43:12+00:00
3,https://complejoteatral.gob.ar/ver/la_gaviota,https://complejoteatral.gob.ar/,event_detail,La Gaviota,"Obra de teatro de Antón Chéjov, dirigida por R...",theatre,None,None,"Teatro San Martín, Sala Casacuberta","Platea $21.000, Miércoles $12.000",False,"[teatro, obra, Antón Chéjov, Rubén Szuchmacher...",0.95,2026-03-16,2026-03-16T11:43:12+00:00
4,https://complejoteatral.gob.ar/ver/jazz_buenos...,https://complejoteatral.gob.ar/,event_detail,Jazz Buenos Aires,Ciclo de nueve conciertos de Jazz at Lincoln C...,music,2026-03-17,20:00,"Teatro San Martín, Sala Martín Coronado","Platea Filas 2 a 5 $85.000, Platea Filas 6 a 2...",False,"[jazz, concierto, música, Jazz at Lincoln Cent...",0.95,2026-03-16,2026-03-16T11:43:12+00:00

In [20]:
df_events.shape

(103, 15)

In [21]:
df_events.groupby("homepage_url")["homepage_url"].count().sort_values(ascending=False)

homepage_url
https://malba.org.ar/                            30
https://turismo.buenosaires.gob.ar/es/eventos    29
https://complejoteatral.gob.ar/                  28
https://www.bellasartes.gob.ar/agenda/           16
Name: homepage_url, dtype: int64

In [22]:
df_events.groupby("category")["homepage_url"].count().sort_values(ascending=False)

category
other         61
theatre       10
cinema         9
exhibition     8
talk           8
workshop       4
music          2
dance          1
Name: homepage_url, dtype: int64

In [19]:
df_events

,url,homepage_url,page_type,title,summary,category,start_date,start_time,venue,price,is_free,tags,confidence,run_date,extracted_at
0,https://complejoteatral.gob.ar/agenda?fecha=16...,https://complejoteatral.gob.ar/,listing,Agenda | Complejo Teatral de Buenos Aires,Listing of theatrical events around 16 March 2...,theatre,None,None,None,None,None,"[teatro, agenda, temporada internacional, comp...",0.80,2026-03-16,2026-03-16T11:43:12+00:00
1,https://complejoteatral.gob.ar/pdf/temporada20...,https://complejoteatral.gob.ar/,pdf,None,None,other,None,None,None,None,None,[],0.30,2026-03-16,2026-03-16T11:43:12+00:00
2,https://complejoteatral.gob.ar/ver/GERALD-CLAY...,https://complejoteatral.gob.ar/,event_detail,GERALD CLAYTON TRIO,Comienza el ciclo de jazz en el Teatro San Mar...,music,2026-03-17,20:00,"Teatro San Martín, Sala Martín Coronado","Platea Filas 2 a 5 $85.000, Platea Filas 6 a 2...",False,"[jazz, Gerald Clayton, Trio, Teatro San Martín...",0.95,2026-03-16,2026-03-16T11:43:12+00:00
3,https://complejoteatral.gob.ar/ver/la_gaviota,https://complejoteatral.gob.ar/,event_detail,La Gaviota,"Obra de teatro de Antón Chéjov, dirigida por R...",theatre,None,None,"Teatro San Martín, Sala Casacuberta","Platea $21.000, Miércoles $12.000",False,"[teatro, obra, Antón Chéjov, Rubén Szuchmacher...",0.95,2026-03-16,2026-03-16T11:43:12+00:00
4,https://complejoteatral.gob.ar/ver/jazz_buenos...,https://complejoteatral.gob.ar/,event_detail,Jazz Buenos Aires,Ciclo de nueve conciertos de Jazz at Lincoln C...,music,2026-03-17,20:00,"Teatro San Martín, Sala Martín Coronado","Platea Filas 2 a 5 $85.000, Platea Filas 6 a 2...",False,"[jazz, concierto, música, Jazz at Lincoln Cent...",0.95,2026-03-16,2026-03-16T11:43:12+00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
98,/agenda/entre-tela/,https://www.bellasartes.gob.ar/agenda/,other,None,None,other,None,None,None,None,None,[],0.10,2026-03-16,2026-03-16T11:43:12+00:00
99,/agenda/catalogo-dibujos-antiguos/,https://www.bellasartes.gob.ar/agenda/,other,None,None,other,None,None,None,None,None,[],0.10,2026-03-16,2026-03-16T11:43:12+00:00
100,/agenda/visita-acc_1/,https://www.bellasartes.gob.ar/agenda/,event_detail,None,None,other,None,None,None,None,None,[],0.10,2026-03-16,2026-03-16T11:43:12+00:00
101,/lang/pt/?path=/agenda/,https://www.bellasartes.gob.ar/agenda/,listing,None,None,other,None,None,None,None,None,[],0.20,2026-03-16,2026-03-16T11:43:12+00:00
102,/lang/en/?path=/agenda/,https://www.bellasartes.gob.ar/agenda/,listing,None,None,other,None,None,None,None,None,[],0.20,2026-03-16,2026-03-16T11:43:12+00:00

In [25]:
pd.set_option('display.max_colwidth', 80)

df_to_rate = df_events[df_events['page_type'] == 'event_detail'][['url', 'title', 'category', 'is_free', 'summary']].reset_index(drop=True)
df_to_rate

,url,title,category,is_free,summary
0,https://complejoteatral.gob.ar/ver/GERALD-CLAYTON-TRIO,GERALD CLAYTON TRIO,music,False,Comienza el ciclo de jazz en el Teatro San Martín con la presentación de Ger...
1,https://complejoteatral.gob.ar/ver/la_gaviota,La Gaviota,theatre,False,"Obra de teatro de Antón Chéjov, dirigida por Rubén Szuchmacher, con traducci..."
2,https://complejoteatral.gob.ar/ver/jazz_buenos_aires,Jazz Buenos Aires,music,False,"Ciclo de nueve conciertos de Jazz at Lincoln Center en el Teatro San Martín,..."
3,https://complejoteatral.gob.ar/ver/los-pilares-de-la-sociedad,LOS PILARES DE LA SOCIEDAD,theatre,False,Obra de teatro de Henrik Ibsen que denuncia la hipocresía moral y social de ...
4,https://complejoteatral.gob.ar/ver/invasiones-1,INVASIONES I,theatre,False,Invasiones I: No Bombardeen Buenos Aires es un musical protagonizado por Ele...
5,https://complejoteatral.gob.ar/ver/paraiso,PARAÍSO,theatre,False,Paraíso es una obra que interpela la masculinidad. Es la historia de Juan Va...
6,https://complejoteatral.gob.ar/ver/baco-polaco,Baco polaco,theatre,False,Obra teatral de Mauricio Kartun que traslada la tragedia Las bacantes de Eur...
7,https://complejoteatral.gob.ar/ver/festival_el_tornillo,FESTIVAL EL TORNILLO - II EDICIÓN,theatre,None,Festival El Tornillo es un encuentro artístico creado y gestionado por los t...
8,https://complejoteatral.gob.ar/ver/centroamerica,CENTROAMÉRICA,theatre,False,Obra teatral del colectivo mexicano Lagartijas Tiradas al Sol que examina la...
9,https://complejoteatral.gob.ar/ver/numancia,NUMANCIA,theatre,False,"Obra teatral dirigida por José Luis Alonso de Santos, inspirada en hechos hi..."
10,https://complejoteatral.gob.ar/ver/viaje-al-amor-brujo,Viaje al amor brujo,dance,False,"Un viaje clásico y flamenco, tradicional y contemporáneo, con música de Manu..."
11,https://complejoteatral.gob.ar/ver/Las-furias-y-Las-modelos,Las furias y Las modelos,cinema,False,"Ciclo de funciones especiales de los largometrajes restaurados ""Las furias"" ..."
12,https://complejoteatral.gob.ar/ver/Boris-Karloff:-el hombre-y-la- bestia - P...,Boris Karloff: el hombre y la bestia - Parte 1,cinema,None,Ciclo de cine dedicado a Boris Karloff con diez films emblemáticos del actor...
13,https://complejoteatral.gob.ar/ver/Garage-Olimpo,Garage Olimpo,cinema,None,"Única función especial del largometraje de Marco Bechis, en conmemoración de..."
14,https://www.timbre4.com/teatro/1241-pasion-una-tragedia-argentina.html,Pasión una tragedia argentina,theatre,None,"Una madre se reencuentra con su hijo, quien llega para confesarle su traició..."
15,https://malba.org.ar/evento/tercer-ojo__coleccion-costantini_en-malba/,Tercer ojo Colección Costantini en Malba,exhibition,None,Una exposición que reúne más de 220 obras icónicas del arte latinoamericano ...
16,https://malba.org.ar/evento/olga-de-amaral-cuerpo-textil/,Olga de Amaral: Cuerpo textil,exhibition,None,Exposición que revisa la práctica artística de Olga de Amaral desde la décad...
17,https://malba.org.ar/evento/fernanda-laguna-mi-corazon-es-un-iman/,Fernanda Laguna: Mi corazón es un imán (1992-2025),exhibition,None,"Exposición retrospectiva de la obra de Fernanda Laguna, artista visual, escr..."
18,https://malba.org.ar/evento/fernanda-laguna-mi-corazon-es-un-iman-1992-2025/,"Conferencia inaugural Fernanda Laguna Mi corazón es un imán, 1992–2025",talk,None,La conferencia inaugural acompañará la apertura de esta retrospectiva para i...
19,https://malba.org.ar/evento/anima-y-animus-en-carl-g-jung-el-desarrollo-psiq...,Ánima y ánimus en Carl G. Jung: el desarrollo psíquico y los opuestos arquet...,talk,False,Seminario intensivo presencial y virtual que aborda la estructura psíquica d...
20,https://malba.org.ar/evento/modos-de-hacer-paisajes-tejidos/,Modos de hacer: Paisajes tejidos,workshop,False,Taller a cargo del equipo educativo centrado en la exposición Cuerpo textil ...
21,https://malba.org.ar/evento/hacer-familia/,Chiachio & Giannone: Hacer familia,exhibition,True,Los artistas Chiachio & Giannone proponen un recorrido por las salas de la e...
22,https://malba.org.ar/evento/el-cuerpo-del-color-el-ikat-tridimensional-de-ol...,El cuerpo del color: el ikat tridimensional de Olga de Amaral,talk,True,Conferencia por Roxana Amarilla sobre la técnica del ikat y su relación con ...
23,https://malba.org.ar/evento/hitchcock-x-4/,Hitchcock x 4,cinema,None,"En el mes de marzo, el tradicional espacio de Cineclub Nocturna los sábados ..."
24,https://malba.org.ar/evento/recorridos-abiertos-por-cuerpo-textil/,Recorridos abiertos por Cuerpo textil,exhibition,False,El equipo educativo propone una serie de recorridos por la exposición dedica...
25,https://malba.org.ar/evento/los-dias-chinos/,Los dias chinos,cinema,None,Un viaje que se ha postergado durante años y un día se concreta. Un plan par...
26,https://malba.org.ar/evento/belleza-y-felicidad-autobiografia-de-una-amistad/,Belleza y Felicidad Autobiografía de una amistad,talk,True,"Presentación de libro con Fernanda Laguna, Cecilia Pavón y Rita Pauls. Un ev..."
27,https://malba.org.ar/evento/cien-anos-mas-tarde-libros-argentinos-de-1926-ar...,"Cien años más tarde: libros argentinos de 1926 — Arlt, Güiraldes, Quiroga y ...",workshop,False,Curso presencial y virtual que revisa cuatro libros argentinos publicados en...
28,https://malba.org.ar/evento/cuerpo-textil/,Conferencia inaugural Cuerpo textil,talk,True,Conferencia inaugural con Marita García y Constanza Martínez como antesala d...
29,https://malba.org.ar/evento/el-arte-de-escribir-una-vida-loca-introduccion-a...,El arte de escribir una vida loca: introducción a la obra literaria de Ferna...,workshop,False,"Curso presencial + virtual que explora la obra literaria de Fernanda Laguna,..."
30,https://malba.org.ar/evento/pin-de-fartie/,Pin de fartie,cinema,None,Una niña y un ciego frente a un lago que borronea los límites del espacio. D...
31,https://malba.org.ar/evento/tardes-de-soledad/,Tardes de soledad,cinema,None,Tardes de soledad es un documental que retrata a una figura central del tore...
32,https://malba.org.ar/inauguracion-olga-de-amaral/,Olga de Amaral. Cuerpo Textil,exhibition,None,"Retrospective exhibition dedicated to Colombian artist Olga de Amaral, featu..."
33,https://malba.org.ar/evento/recorridos-abiertos-en-portugues__tupi-or-not-tu...,Trajetos brasileiros na arte latino-americana,exhibition,False,Recorrido en portugués que sitúa las icónicas obras del arte brasileño en el...
34,https://malba.org.ar/evento/telares-como-textos-piel-social-de-la-cultura-an...,Telares como textos: piel social de la cultura andina,talk,False,Seminario intensivo presencial y virtual que invita a leer los textiles andi...
35,https://malba.org.ar/rem-2026__los-autores-seleccionados-para-participar-de-...,REM 2026__Cinco autores seleccionados para participar de la Residencia de Es...,talk,None,La Residencia de Escritores de Malba (REM) anuncia la visita de cinco escrit...
36,/es/node/72956,None,other,None,None
37,/es/node/72264,None,other,None,None
38,/es/node/67111,None,other,None,None
39,/es/node/70621,None,other,None,None
40,/agenda/circulacion-en-planta-baja-con-sentido-unico/,None,other,None,None
41,/agenda/visitas-egipt/,None,other,None,None
42,/agenda/lsa-egipt/,None,other,None,None
43,/agenda/boceto-egipto/,None,other,None,None
44,/agenda/recorrido-por-la-planta-baja-y-primer-piso/,None,other,None,None
45,/agenda/visita-acc_1/,None,other,None,None

In [30]:

liked = [0,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,0,0,1,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0]

df_to_rate['liked'] = liked
df_to_rate.to_csv("../data/processed/user_ratings.csv", index=False)